# Send interval (Unit: second)
# Sender stops when set to 0.
# Please set it to 0 if you want to stop by maintenance etc.
Interval: 60

# Use to monitor multiple servers.
# Sends the value specified here as an argument.
# Example:
# Identifier: "Minecraft" -> "minecraft.tps[Minecraft]"
# Identifier: "Zabbigot" -> "minecraft.tps[Zabbigot]"
Identifier: "Minecraft"

Zabbix:
  Server: "localhost"
  Port: 10051
  Hostname: "MinecraftServer"